# Generated by Django 6.0.1 on 2026-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reminder_active', models.BooleanField(default=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('last_reminder_21_date', models.DateField(blank=True, null=True)),
                ('last_reminder_22_date', models.DateField(blank=True, null=True)),
                ('last_reminder_23_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'App settings',
                'db_table': 'app_settings',
            },
        ),
    ]
