# Generated by Django 6.0.1 on 2026-01-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_app_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('is_reminder_active', models.BooleanField(default=True)),
                ('last_reminder_21_date', models.DateField(blank=True, null=True)),
                ('last_reminder_22_date', models.DateField(blank=True, null=True)),
                ('last_reminder_23_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User settings',
                'db_table': 'user_settings',
            },
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='core.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercisechallenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_types', to='core.appuser'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.appuser'),
        ),
        migrations.AddConstraint(
            model_name='exercisetype',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_exercise_type_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.UniqueConstraint(fields=('user', 'exercise_type'), name='unique_stats_per_user_exercise'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.appuser'),
        ),
    ]
