# Generated by Django 6.0.1 on 2026-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_backfill_default_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="is_registration_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_registration_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
